apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
- token: "123456.1234567890123456"
  ttl: "0s"
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: "192.168.10.100"
nodeRegistration:
  kubeletExtraArgs:
    - name: node-ip
      value: "192.168.10.100"
  criSocket: "unix:///run/containerd/containerd.sock"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: PLACEHOLDER_K8S_VERSION
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"