# Variables
K8SV = '1.33.2' # Kubernetes Version
K8S_APT_VERSION = '1.33.2-1.1' # Kubernetes APT Version : apt list -a kubelet , ex) 1.32.5-1.1
CONTAINERDV = '1.7.27-1' # Containerd Version : apt list -a containerd.io , ex) 1.6.33-1
CILIUMV = '1.18.0' # Cilium CNI Version : https://github.com/cilium/cilium/tags
N = 1 # max number of worker nodes

# Base Image  https://portal.cloud.hashicorp.com/vagrant/discover/bento/ubuntu-24.04
## Rocky linux Image https://portal.cloud.hashicorp.com/vagrant/discover/rockylinux
BOX_IMAGE = "bento/ubuntu-24.04"
BOX_VERSION = "202502.21.0"

Vagrant.configure("2") do |config|
#-ControlPlane Node
    config.vm.define "cilium-ctr" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--groups", "/Cilium-Lab-W5"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.name = "cilium-ctr"
        vb.cpus = 2
        vb.memory = 2560
        vb.linked_clone = true
      end
      subconfig.vm.host_name = "cilium-ctr"
      subconfig.vm.network "private_network", ip: "192.168.60.100"
      subconfig.vm.network "forwarded_port", guest: 22, host: 60000, auto_correct: true, id: "ssh"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.provision "file", source: "kubeadm-config.yaml", destination: "/home/vagrant/kubeadm-config.yaml"
      subconfig.vm.provision "shell", path: "init_cfg.sh", args: [ K8S_APT_VERSION, CONTAINERDV]
      subconfig.vm.provision "shell", path: "cilium-ctr.sh", args: [ K8SV, CILIUMV, N ]
      subconfig.vm.provision "shell", path: "net-setting-01.sh"
    end

#-Router Node
  config.vm.define "cilium-r" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/Cilium-Lab-W5"]
      vb.name = "cilium-r"
      vb.cpus = 1
      vb.memory = 1024
      vb.linked_clone = true
    end
    subconfig.vm.host_name = "cilium-r"
    subconfig.vm.network "private_network", ip: "192.168.60.200"
    subconfig.vm.network "private_network", ip: "192.168.20.200", auto_config: false
    subconfig.vm.network "forwarded_port", guest: 22, host: 60009, auto_correct: true, id: "ssh"
    subconfig.vm.synced_folder "./", "/vagrant", disabled: true
    subconfig.vm.provision "shell", path: "cilium-r.sh"
  end

#-Worker Nodes Subnet1
  (1..N).each do |i|
    config.vm.define "cilium-w#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.box_version = BOX_VERSION
      subconfig.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--groups", "/Cilium-Lab-W5"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.name = "cilium-w#{i}"
        vb.cpus = 2
        vb.memory = 2048
        vb.linked_clone = true
      end
      subconfig.vm.host_name = "cilium-w#{i}"
      subconfig.vm.network "private_network", ip: "192.168.60.10#{i}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "6000#{i}", auto_correct: true, id: "ssh"
      subconfig.vm.synced_folder "./", "/vagrant", disabled: true
      subconfig.vm.provision "file", source: "kubeadm-join-config.yaml", destination: "/home/vagrant/kubeadm-join-config.yaml"
      subconfig.vm.provision "shell", path: "init_cfg.sh", args: [ K8S_APT_VERSION, CONTAINERDV]
      subconfig.vm.provision "shell", path: "cilium-w.sh"
      subconfig.vm.provision "shell", path: "net-setting-01.sh"
    end
  end

#-Worker Nodes Subnet2
  config.vm.define "cilium-w3" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.box_version = BOX_VERSION
    subconfig.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/Cilium-Lab-W5"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.name = "cilium-w3"
      vb.cpus = 2
      vb.memory = 2048
      vb.linked_clone = true
    end
    subconfig.vm.host_name = "cilium-w3"
    subconfig.vm.network "private_network", ip: "192.168.160.100"
    subconfig.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    subconfig.vm.synced_folder "./", "/vagrant", disabled: true
    subconfig.vm.provision "file", source: "kubeadm-join-config.yaml", destination: "/home/vagrant/kubeadm-join-config.yaml"
    subconfig.vm.provision "shell", path: "init_cfg.sh", args: [ K8S_APT_VERSION, CONTAINERDV]
    subconfig.vm.provision "shell", path: "cilium-w.sh"
    subconfig.vm.provision "shell", path: "net-setting-02.sh"
  end

end
